version: "3.8"

services:
  db:
    image: postgres:16.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: api
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/frontend/app
    command: sh -c "cd /frontend/app && PORT=8000 yarn start"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  smtp:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
